version: "3.9"
services:
  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: fastapi-server
  streamlit-server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    container_name: streamlit-server
